"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-27 20:24:36.022379
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_master_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('sac_code', sa.String(), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('calculation_basis', sa.Enum('FLAT', 'PER_CONTAINER', 'PER_KG', name='chargecalculationbasis', native_enum=False, length=40), nullable=False),
    sa.Column('default_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('charge_master_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charge_master_entries_id'), ['id'], unique=False)

    op.create_table('hs_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hs_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hs_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_hs_codes_id'), ['id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_code', sa.String(length=7), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_ad_code'), ['ad_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'IMPORT_MANAGER', 'EXPORT_MANAGER', 'ACCOUNTANT', name='userrole', native_enum=False, length=40), nullable=False),
    sa.Column('can_access_billing', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('audit_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entries_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entries_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entries_table_name'), ['table_name'], unique=False)

    op.create_table('required_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hs_code_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('CFS_PROFORMA_INVOICE', 'CFS_TAX_INVOICE', 'ASSESSED_BILL_OF_ENTRY', 'OOC_BILL_OF_ENTRY', 'GATEPASS_BILL_OF_ENTRY', 'BL_COPY', 'HBL_COPY', 'PACKING_LIST', 'INSURANCE', 'DO_LETTER', 'EMPTY_LETTER', 'HSS_STAMP_DUTY', 'CERTIFICATE_OF_ORIGIN', 'FTA_CERTIFICATE_OF_ORIGIN', 'FORM_6', 'FORM_9', 'OTHER', name='documenttype', native_enum=False, length=40), nullable=False),
    sa.ForeignKeyConstraint(['hs_code_id'], ['hs_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('required_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_required_documents_id'), ['id'], unique=False)

    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(), nullable=False),
    sa.Column('mbl', sa.String(), nullable=False),
    sa.Column('hbl', sa.String(), nullable=True),
    sa.Column('be_no', sa.String(), nullable=True),
    sa.Column('be_dt', sa.Date(), nullable=True),
    sa.Column('be_description', sa.String(), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('inw', sa.String(), nullable=True),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('consignee', sa.String(), nullable=True),
    sa.Column('pod', sa.String(), nullable=True),
    sa.Column('container_status', sa.String(), nullable=True),
    sa.Column('cfs', sa.String(), nullable=True),
    sa.Column('container', sa.String(), nullable=True),
    sa.Column('gross_wt', sa.String(), nullable=True),
    sa.Column('poc', sa.String(), nullable=True),
    sa.Column('cleared_date', sa.Date(), nullable=True),
    sa.Column('igm', sa.String(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.Column('duty_paid', sa.Boolean(), nullable=False),
    sa.Column('cfs_inv_received', sa.Boolean(), nullable=False),
    sa.Column('line_paid', sa.Boolean(), nullable=False),
    sa.Column('ooc', sa.Boolean(), nullable=False),
    sa.Column('do', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_stuck', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('TO_BE_FILED', 'IGM_FILED', 'BE_FILED', 'BE_ASSESSED', 'DUTY_PAID', 'UNDER_OOC', 'OOC_DONE', 'CLEARED', 'BILLED', name='shipmentstatus', native_enum=False, length=40), nullable=False),
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('hs_code_id', sa.Integer(), nullable=True),
    sa.Column('is_billed', sa.Boolean(), nullable=False),
    sa.Column('billed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hs_code_id'], ['hs_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_be_no'), ['be_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_hbl'), ['hbl'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_job'), ['job'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_mbl'), ['mbl'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_port'), ['port'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_status'), ['status'], unique=False)

    op.create_table('user_port_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('port', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_port_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_port_access_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_port_access_port'), ['port'], unique=False)

    op.create_table('proformas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'SUPERSEDED', name='proformastatus', native_enum=False, length=40), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('generated_filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proformas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proformas_id'), ['id'], unique=False)

    op.create_table('shipment_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('CFS_PROFORMA_INVOICE', 'CFS_TAX_INVOICE', 'ASSESSED_BILL_OF_ENTRY', 'OOC_BILL_OF_ENTRY', 'GATEPASS_BILL_OF_ENTRY', 'BL_COPY', 'HBL_COPY', 'PACKING_LIST', 'INSURANCE', 'DO_LETTER', 'EMPTY_LETTER', 'HSS_STAMP_DUTY', 'CERTIFICATE_OF_ORIGIN', 'FTA_CERTIFICATE_OF_ORIGIN', 'FORM_6', 'FORM_9', 'OTHER', name='documenttype', native_enum=False, length=40), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('generated_filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('tracker_sync_applied', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_documents_id'), ['id'], unique=False)

    op.create_table('proforma_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proforma_id', sa.Integer(), nullable=False),
    sa.Column('charge_master_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sac_code', sa.String(), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['charge_master_id'], ['charge_master_entries.id'], ),
    sa.ForeignKeyConstraint(['proforma_id'], ['proformas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proforma_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proforma_line_items_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proforma_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proforma_line_items_id'))

    op.drop_table('proforma_line_items')
    with op.batch_alter_table('shipment_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_documents_id'))

    op.drop_table('shipment_documents')
    with op.batch_alter_table('proformas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proformas_id'))

    op.drop_table('proformas')
    with op.batch_alter_table('user_port_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_port_access_port'))
        batch_op.drop_index(batch_op.f('ix_user_port_access_id'))

    op.drop_table('user_port_access')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_status'))
        batch_op.drop_index(batch_op.f('ix_shipments_port'))
        batch_op.drop_index(batch_op.f('ix_shipments_mbl'))
        batch_op.drop_index(batch_op.f('ix_shipments_job'))
        batch_op.drop_index(batch_op.f('ix_shipments_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_hbl'))
        batch_op.drop_index(batch_op.f('ix_shipments_be_no'))

    op.drop_table('shipments')
    with op.batch_alter_table('required_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_required_documents_id'))

    op.drop_table('required_documents')
    with op.batch_alter_table('audit_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_table_name'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_record_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entries_changed_at'))

    op.drop_table('audit_log_entries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_id'))
        batch_op.drop_index(batch_op.f('ix_organizations_ad_code'))

    op.drop_table('organizations')
    with op.batch_alter_table('hs_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hs_codes_id'))
        batch_op.drop_index(batch_op.f('ix_hs_codes_code'))

    op.drop_table('hs_codes')
    with op.batch_alter_table('charge_master_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charge_master_entries_id'))

    op.drop_table('charge_master_entries')
    # ### end Alembic commands ###
