"""tracker sheet columns and ports

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-27 20:24:54.277177
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ports_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_ports_id'), ['id'], unique=False)

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remark', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mbl_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('hbl_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gw', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('total_pkg', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pkg_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('line_no', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('igm_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('voyage', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cont', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('shipping_line', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_column('shipping_line')
        batch_op.drop_column('cont')
        batch_op.drop_column('voyage')
        batch_op.drop_column('igm_date')
        batch_op.drop_column('line_no')
        batch_op.drop_column('pkg_code')
        batch_op.drop_column('total_pkg')
        batch_op.drop_column('gw')
        batch_op.drop_column('hbl_date')
        batch_op.drop_column('mbl_date')
        batch_op.drop_column('remark')

    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ports_id'))
        batch_op.drop_index(batch_op.f('ix_ports_code'))

    op.drop_table('ports')
    # ### end Alembic commands ###
