"""custom tracker columns

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-27 20:44:13.496283
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracker_columns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracker_columns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracker_columns_key'), ['key'], unique=True)

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_fields', sa.JSON(), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_column('custom_fields')

    with op.batch_alter_table('tracker_columns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracker_columns_key'))
        batch_op.drop_index(batch_op.f('ix_tracker_columns_id'))

    op.drop_table('tracker_columns')
    # ### end Alembic commands ###
