"""document extraction fields

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-27 22:03:33.423951
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extraction', sa.JSON(), nullable=True))

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessable_value', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('igst_amount', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('duty_amount', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('cfs_amount_before_tax', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('cfs_gst_amount', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('cfs_amount_total', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('ooc_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('under_examination', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('examination_at', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_column('examination_at')
        batch_op.drop_column('under_examination')
        batch_op.drop_column('ooc_date')
        batch_op.drop_column('cfs_amount_total')
        batch_op.drop_column('cfs_gst_amount')
        batch_op.drop_column('cfs_amount_before_tax')
        batch_op.drop_column('duty_amount')
        batch_op.drop_column('igst_amount')
        batch_op.drop_column('assessable_value')

    with op.batch_alter_table('shipment_documents', schema=None) as batch_op:
        batch_op.drop_column('extraction')

    # ### end Alembic commands ###
