"""document checklist changes

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-27 22:05:44.150705
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('required_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optional', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###

    # Client feedback on the document checklist (enum values are stored by name):
    #  - Form 6 and Form 9 arrive as one merged document
    #  - HSS Agreement and Stamp Duty are two separate documents
    #  - Empty Letter is often inside the DO letter -> optional
    conn = op.get_bind()
    for (hs_id,) in conn.execute(sa.text(
            "SELECT DISTINCT hs_code_id FROM required_documents WHERE document_type IN ('FORM_6','FORM_9')")).fetchall():
        conn.execute(sa.text("DELETE FROM required_documents WHERE hs_code_id=:h AND document_type IN ('FORM_6','FORM_9')"), {"h": hs_id})
        conn.execute(sa.text("INSERT INTO required_documents (hs_code_id, document_type, optional) VALUES (:h, 'FORM_6_9', FALSE)"), {"h": hs_id})
    for (hs_id,) in conn.execute(sa.text(
            "SELECT DISTINCT hs_code_id FROM required_documents WHERE document_type = 'HSS_STAMP_DUTY'")).fetchall():
        conn.execute(sa.text("UPDATE required_documents SET document_type='HSS_AGREEMENT' WHERE hs_code_id=:h AND document_type='HSS_STAMP_DUTY'"), {"h": hs_id})
        conn.execute(sa.text("INSERT INTO required_documents (hs_code_id, document_type, optional) VALUES (:h, 'STAMP_DUTY', FALSE)"), {"h": hs_id})
    conn.execute(sa.text("UPDATE required_documents SET optional=TRUE WHERE document_type='EMPTY_LETTER'"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('required_documents', schema=None) as batch_op:
        batch_op.drop_column('optional')

    # ### end Alembic commands ###
