"""cfs paid by us and tds flags

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-27 22:11:12.441931
"""
from alembic import op
import sqlalchemy as sa


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cfs_paid_by_us', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('tds_deducted', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('tds_on_cfs', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_column('tds_on_cfs')
        batch_op.drop_column('tds_deducted')
        batch_op.drop_column('cfs_paid_by_us')

    # ### end Alembic commands ###
