"""drive links on documents

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-27 22:13:34.903130
"""
from alembic import op
import sqlalchemy as sa


revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_file_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('drive_link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_documents', schema=None) as batch_op:
        batch_op.drop_column('drive_link')
        batch_op.drop_column('drive_file_id')

    # ### end Alembic commands ###
