"""shipment drive folder

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-27 22:18:36.630955
"""
from alembic import op
import sqlalchemy as sa


revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_folder_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('drive_folder_link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_column('drive_folder_link')
        batch_op.drop_column('drive_folder_id')

    # ### end Alembic commands ###
