"""cfs invoice amounts per document

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-27 22:33:49.458109
"""
from alembic import op
import sqlalchemy as sa


revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_before_tax', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('amount_total', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('amounts_edited', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###

    # Backfill: CFS invoices uploaded before this change get the amounts that
    # were read from them (kept in the `extraction` JSON).
    import json
    from decimal import Decimal
    conn = op.get_bind()
    rows = conn.execute(sa.text(
        "SELECT id, extraction FROM shipment_documents "
        "WHERE document_type IN ('CFS_TAX_INVOICE', 'CFS_PROFORMA_INVOICE') AND extraction IS NOT NULL")).fetchall()
    for doc_id, raw in rows:
        fields = (json.loads(raw) if isinstance(raw, str) else raw or {}).get("fields") or {}
        before, gst, after = fields.get("cfs_before_tax"), fields.get("cfs_gst"), fields.get("cfs_after_tax")
        total = Decimal(str(before)) + Decimal(str(gst)) if before is not None and gst is not None else after
        conn.execute(sa.text("UPDATE shipment_documents SET amount_before_tax=:b, gst_amount=:g, amount_total=:t "
                             "WHERE id=:i"),
                     {"b": before, "g": gst, "t": None if total is None else str(total), "i": doc_id})


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_documents', schema=None) as batch_op:
        batch_op.drop_column('amounts_edited')
        batch_op.drop_column('amount_total')
        batch_op.drop_column('gst_amount')
        batch_op.drop_column('amount_before_tax')

    # ### end Alembic commands ###
